---

- name: cisco change interface
  hosts: switches
  gather_facts: false

- name: Merge provided configuration with device configuration
  cisco.ios.ios_interfaces:
    config:
      - name: GigabitEthernet1/0/1
        description: Configured and Merged by Ansible Network
        enabled: true
      - name: GigabitEthernet1/0/2
        description: Configured and Merged by Ansible Network
        mtu: 3800
        enabled: false
        speed: 100
        duplex: full
    state: merged