---

- name: cisco change interface
  hosts: switches
  gather_facts: false

  tasks:
    - name: Merge provided configuration with device configuration
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1/0/1
            description: Configured and Merged by Ansible Network
            enabled: true
          - name: GigabitEthernet1/0/2
            description: Configured and Merged by Ansible Network
            enabled: false
            speed: 100
            duplex: full
        state: merged

    - name: Apply the provided configuration
      cisco.ios.ios_hostname:
        config: 
          hostname: coreswitch
        state: merged    